# Generated by Django 2.2.13 on 2021-06-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('lat', models.FloatField(max_length=100)),
                ('lon', models.FloatField(max_length=100)),
            ],
        ),
    ]
